version: '3'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  # Backend service
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: "mongodb+srv://admin:admin123@cluster0.nensk3k.mongodb.net/?retryWrites=true&w=majority"
      JWT_SECRET: "secret"

    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
