version: '3.9'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - server

  # Backend service
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env

    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
